highlighter: pygments
github_username: sosolimited

# Build Settings
markdown: redcarpet
markdown_ext: markdown,md,mkdown,mkdn,mkd

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]