safe: true
highlighter: pygments
github_username: sosolimited
title: Soso Web Handbook

# Get absolute paths to work
baseurl: "http://sosolimited.github.io/Web-Handbook"

# Build Settings
markdown: redcarpet
markdown_ext: markdown,md,mkdown,mkdn,mkd

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]